---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
    - step: be-a-dummy
      functionRef:
        name: function-dummy
      input:
        apiVersion: dummy.fn.crossplane.io/v1beta1
        kind: Response
        # This is a YAML-serialized RunFunctionResponse. function-dummy will
        # overlay the desired state on any that was passed into it.
        response:
          desired:
            resources:
              named:
                resource:
                  apiVersion: nop.crossplane.io/v1alpha1
                  kind: NopResource
                  metadata:
                    name: named
                  spec:
                    forProvider: {}
              no-name:
                resource:
                  apiVersion: nop.crossplane.io/v1alpha1
                  kind: NopResource
                  spec:
                    forProvider: {}
              annotated:
                resource:
                  apiVersion: nop.crossplane.io/v1alpha1
                  kind: NopResource
                  metadata:
                    name: named
                    annotations:
                      crossplane.io/external-name: annotated
                  spec:
                    forProvider: {}
    - step: external-namer
      functionRef:
        name: function-external-namer